AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post Service
Resources:

  PostServiceRead:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: post-service-read
      Policies: 
        - AWSLambdaFullAccess
      Handler: read.handler
      Runtime: nodejs6.10
      CodeUri: ./.webpack
      Events:
        GETResource:
          Type: Api
          Properties:
            Path: /
            Method: get