AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Post Service
Resources:

  PostServiceCreate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: post-service-create
      Policies: 
        - AWSLambdaFullAccess
      Handler: create.handler
      Runtime: nodejs6.10
      CodeUri: ./.webpack
    Events:
      Type: Api
      Properties:
        Path: /
        Method: post