version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g webpack
  pre_build:
    commands:
      - echo "Pre Build Running"
  build:
    commands:
      - echo "Build Running"
      - cd ./$SERVICE
      - webpack
  post_build:
    commands:
      - echo "Post Build Running"
      - aws cloudformation package --template-file ./service.yml --output-template-file ./.sam/package-service.yml --s3-bucket ej-asia-demo
artifacts:
  files:
    - post-service/.sam/package-service.yml
  discard-paths: yes