version: 0.2

phases:
  install:
    commands:
      - npm install
      - chmod 777 ./bin/*
      - ./bin/install.js
  pre_build:
    commands:
      - echo "Pre Build Running"
  build:
    commands:
      - echo "Build Running"
  post_build:
    commands:
      - echo "Post Build Running"
