version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g webpack
  pre_build:
    commands:
      - echo "Pre Build Running"
  build:
    commands:
      - echo "Build Running"
      - cd ./$SERVICE
      - webpack
  post_build:
    commands:
      - aws cloudformation package --template-file ./service.yml --output-template-file ./.sam/service-packaged.yml --s3-bucket ej-asia-demo
      - echo "Post Build Running"
artifacts:
  files:
    - .sam/service-packaged.yml
  discard-paths: yes