AWSTemplateFormatVersion: '2010-09-09'
Description: Base Infrastructure

Parameters:
  CFTBucket:
    Type: String
    Description: S3 bucket containing CFT files

Resources:
  ## Generic Notification Topic
  NotificationSNS:
    Type: "AWS::SNS::Topic"

  ## My Subscription
  EJSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: me@singledigit.net
      Protocol: email
      TopicArn: !Ref NotificationSNS
  
  ## Generic Build Role
  BuildRole:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${bucket}/nested/build-role.yml
        - {bucket: !Ref CFTBucket}

  ## Event Rules (Coming Soon)
  # CodebuildEvents:
  #   Type: "AWS::Events::Rule"
  #   Properties: 
  #     EventPattern: {"source": ["aws.codebuild"]}
  #     Targets:
  #       - Arn: !Ref NotificationSNS
  #         Id: Codebuild-Events
  
  # CloudFormationEvents:
  #   Type: "AWS::Events::Rule"
  #   Properties: 
  #     EventPattern: {"source": ["aws.cloudformation"]}
  #     Targets:
  #       - Arn: !Ref NotificationSNS
  #         Id: CloudFormation-Events


## Stack Output
Outputs:
  SNSTopicArn:
    Value: !Ref NotificationSNS
    Export:
      Name: NotificationTopicArn

  BuildRoleArn:
    Value: !GetAtt BuildRole.Outputs.BuildRoleArn
    Export:
      Name: BuildRoleArn