AWSTemplateFormatVersion: '2010-09-09'
Description: Base Infrastructure

Parameters:
  CFTBucket:
    Type: String
    Description: S3 bucket containing CFT files
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  Repo:
    Type: String
    Description: GitHub Repo
  Branch:
    Type: String
    Description: GitHub Branch

Resources:
  ## Generic Notification Topic
  NotificationSNS:
    Type: "AWS::SNS::Topic"
  
  ## Generic Build Role
  BuildRole:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${bucket}/nested/build-role.yml
        - {bucket: !Ref CFTBucket}

  PipelineStarted:
    Type: "AWS::Events::Rule"
    Properties: 
      EventPattern: {"source": ["aws.codepipeline"],"detail-type": ["AWS API Call via CloudTrail"],"detail": {"eventSource": ["codepipeline.amazonaws.com"]}}
      Targets:
        - Arn: !Ref NotificationSNS
          Id: Pipeline-Start
          InputTransformer:
            InputPathsMap: {"pipeline":"$.detail.requestParameters.name","user":"$.detail.userIdentity.userName"}
            InputTemplate: "The Pipeline, <pipeline> was kicked off by <user>."

  PipelineFailedEventAlert:
    Type: "AWS::Events::Rule"
    Properties: 
      EventPattern: {"source": ["aws.codepipeline"]}
      Targets:
        - Arn: !Ref NotificationSNS
          Id: Codebuild-Error

Outputs:
  SNSTopicArn:
    Value: !Ref NotificationSNS
    Export:
      Name: NotificationTopicArn

  BuildRoleArn:
    Value: !GetAtt BuildRole.Outputs.BuildRoleArn
    Export:
      Name: BuildRoleArn