AWSTemplateFormatVersion: '2010-09-09'
Description: Base Infrastructure

Parameters:
  CFTBucket:
    Type: String
    Description: S3 bucket containing CFT files
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  Repo:
    Type: String
    Description: GitHub Repo
  Branch:
    Type: String
    Description: GitHub Branch

Resources:
  ## Generic Notification Topic
  NotificationSNS:
    Type: "AWS::SNS::Topic"
  
  ## Generic Build Role
  BuildRole:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${bucket}/nested/build-role.yml
        - {bucket: !Ref CFTBucket}

  PipelineFailedEventAlert:
    Type: "AWS::Events::Rule"
    Properties: 
      EventPattern: {"source": ["aws.codebuild"],"detail": {"completed-phase-status": ["FAILED"]}}
      Targets:
        - Arn: !Ref NotificationSNS
          Id: My-Rule-Target

Outputs:
  SNSTopicArn:
    Value: !Ref NotificationSNS
    Export:
      Name: NotificationTopicArn

  BuildRoleArn:
    Value: !GetAtt BuildRole.Outputs.BuildRoleArn
    Export:
      Name: BuildRoleArn