AWSTemplateFormatVersion: '2010-09-09'
Description: Post Service
Resources:
  PostServiceRead:
    Properties:
      CodeUri: s3://ej-blog-cft/iamsam/8781dd300216537c27eac6b06bff0712
      Events:
        GETResource:
          Properties:
            Method: get
            Path: /
          Type: Api
      FunctionName: post-service-read
      Handler: read.handler
      Policies:
      - AWSLambdaFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
