AWSTemplateFormatVersion: '2010-09-09'
Description: Post Service
Resources:
  PostServiceCreate:
    Properties:
      CodeUri: s3://ej-asia-demo/9bd3c9fb892c6b10268078c7348bb4c5
      Environment:
        Variables:
          POSTS_TABLE:
            Ref: PostsTable
      FunctionName: post-service-create
      Handler: create.handler
      Policies:
      - AWSLambdaFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  PostsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: category
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: category
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
