AWSTemplateFormatVersion: "2010-09-09"
Description: Service CICD

Parameters:
  CFTBucket:
    Type: String
    Description: S3 bucket containing CFT files
  Environment:
    Type: String
    Description: Environment to build for
    Default: dev
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  GitHubToken:
    Type: String
    Description: GitHub Token
  Repo:
    Type: String
    Description: GitHub Repo
  Branch:
    Type: String
    Description: GitHub Branch

Resources:
  BuildArtifactsBucket:
    Type: "AWS::S3::Bucket"

  BuildPipeLine:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location: !Ref BuildArtifactsBucket
        Type: S3
      RoleArn: !ImportValue BuildRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuiltOutput
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: CICD-Agent
      Description: Manages CICD for services
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      ServiceRole: !ImportValue BuildRoleArn
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/nodejs:6.3.1'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
            - Name: SERVICE
              Value: agent-service
            - Name: CFT_BUCKET
              Value: !Ref CFTBucket
            - Name: ENVIRONMENT
              Value: !Ref Environment
            - Name: GITHUB_OWNER
              Value: !Ref GitHubOwner
            - Name: REPO
              Value: !Ref Repo
            - Name: BRANCH
              Value: !Ref Branch
            - Name: GITHUB_TOKEN
              Value: !Ref GitHubToken