AWSTemplateFormatVersion: "2010-09-09"
Description: Service CICD

Parameters:
  Service:
    Type: String
    Description: Name of service
  Environment:
    Type: String
    Description: Environment to build for
    Default: dev
  GitHubOwner:
    Type: String
    Description: GitHub Owner Name
  GitHubToken:
    Type: String
    Description: GitHub Token
  Repo:
    Type: String
    Description: GitHub Repo
  Branch:
    Type: String
    Description: GitHub Branch

Resources:
  BuildArtifactsBucket:
    Type: "AWS::S3::Bucket"

  PackageArtifactsBucket:
    Type: "AWS::S3::Bucket"

  BuildPipeLine:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location: !Ref BuildArtifactsBucket
        Type: S3
      RoleArn: !ImportValue BuildRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repo
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuiltOutput
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuiltOutput
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: !Join [ -, [ !Ref Service, changeset ] ]
                OutputFileName: !Join [ -, [ !Ref Service, output.json ] ]
                Capabilities: CAPABILITY_IAM
                RoleArn: !ImportValue BuildRoleArn
                StackName: !Ref Service
                TemplatePath: BuiltOutput::service-packaged.yml
              RunOrder: 1
            - Name: ExecuteChangeset
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Join [ -, [ !Ref Service, changeset ] ]
                StackName: !Ref Service
              RunOrder: 2

  BuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: !Sub ${Service}-Build-Project
      Description: !Sub Build project for ${Service}
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/nodejs:6.3.1'
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: SERVICE
            Value: !Ref Service
          - Name: BUCKET
            Value: !Ref PackageArtifactsBucket
      ServiceRole: !ImportValue BuildRoleArn