AWSTemplateFormatVersion: '2010-09-09'
Description: 'Generic Build Role'

Resources:
  BuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - cloudformation.amazonaws.com
                - codebuild.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: BuildRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'cloudformation:*'
                  - 'sqs:*'
                  - 'iam:PassRole'
                  - 'logs:*'
                  - 'codebuild:*'
                  - 'codepipeline:*'
                  - 'dynamodb:*'
                  - 'events:*'
                  - 'lambda:*'
                  - "iam:*"
                  - 'apigateway:*'
                  - 'ec2:*'
                Resource: '*'

Outputs:
  BuildRoleArn:
    Value: !GetAtt BuildRole.Arn